import type { Experiment, Capability, Tool, Relation } from './types'

export const capabilities: Capability[] = [
  {
    id: 'technical-seo',
    name: 'Technical SEO',
    maturity: 90,
    color: '#6366f1',
    description: 'Crawl, indexation, robots.txt, sitemaps, Core Web Vitals',
  },
  {
    id: 'keyword-intel',
    name: 'Keyword Intelligence',
    maturity: 85,
    color: '#8b5cf6',
    description: 'Keyword universe, competitor gap, historical rankings, clustering',
  },
  {
    id: 'seo-benchmark',
    name: 'SEO Benchmark',
    maturity: 80,
    color: '#06b6d4',
    description: 'Competitive SERP analysis, ranking tracking, share of voice',
  },
  {
    id: 'content-intel',
    name: 'Content Intelligence',
    maturity: 65,
    color: '#10b981',
    description: 'Content gaps, opportunity scoring, semantic clustering, intent',
  },
  {
    id: 'geo-sources',
    name: 'GEO Sources',
    maturity: 70,
    color: '#f59e0b',
    description: 'LLM source analysis, citation frequency, source taxonomy',
  },
  {
    id: 'offsite-geo',
    name: 'Offsite GEO',
    maturity: 60,
    color: '#f97316',
    description: 'Reddit, YouTube, publisher impact on LLM visibility',
  },
  {
    id: 'agentic',
    name: 'Agentic Visibility',
    maturity: 40,
    color: '#ef4444',
    description: 'MCP, ARD, Knowledge Graphs, agentic service discovery',
  },
]

export const tools: Tool[] = [
  {
    id: 'dataforseo',
    name: 'DataForSEO',
    type: 'api',
    description: 'SEO data API — rankings, SERPs, historical data',
    url: 'https://dataforseo.com',
  },
  {
    id: 'semactic',
    name: 'Semactic',
    type: 'platform',
    description: 'GEO visibility and source monitoring platform',
  },
  {
    id: 'seoctopus',
    name: 'SEOctopus',
    type: 'internal',
    description: 'Internal competitive benchmark tool',
  },
  {
    id: 'reddit-api',
    name: 'Reddit API',
    type: 'api',
    description: 'Reddit post/comment extraction and analysis',
  },
  {
    id: 'python',
    name: 'Python / DuckDB',
    type: 'library',
    description: 'Analysis scripts, local querying, data transformation',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    type: 'platform',
    description: 'PostgreSQL database — storing results and experiments',
    url: 'https://supabase.com',
  },
  {
    id: 'screaming-frog',
    name: 'Screaming Frog',
    type: 'platform',
    description: 'Website crawler for technical SEO audits',
  },
  {
    id: 'openai',
    name: 'OpenAI / Anthropic',
    type: 'api',
    description: 'LLM APIs for analysis, classification, GEO testing',
  },
  {
    id: 'gsc',
    name: 'Google Search Console',
    type: 'api',
    description: 'Search performance data, clicks, impressions, CTR',
  },
]

export const experiments: Experiment[] = [
  {
    id: 'reddit-source-impact',
    name: 'Reddit Source Impact Analysis',
    capability_id: 'offsite-geo',
    status: 'validated',
    decision: 'deepen',
    value: 4,
    maturity: 3,
    question:
      "Can we measure whether a Reddit comment appearing in LLM sources precedes an increase in that subreddit's presence in AI responses?",
    learnings: [
      {
        text: 'Exact URL analysis is too restrictive — too few matches at scale',
        type: 'finding',
      },
      {
        text: 'Subreddit-level evolution is more robust than exact URL attribution',
        type: 'finding',
      },
      {
        text: 'Temporal correlation is measurable via before/after comparison',
        type: 'finding',
      },
      {
        text: 'Causality cannot be demonstrated — correlation only',
        type: 'warning',
      },
    ],
    inputs: ['Semactic GEO sources', 'Reddit URLs', 'Source dates', 'Subreddit metadata'],
    tool_ids: ['semactic', 'reddit-api', 'python', 'supabase'],
    clients: ['Decathlon BE FR', 'Decathlon BE NL'],
    related_ids: ['llm-citation-freq', 'geo-source-analysis', 'youtube-source'],
    next_experiment:
      'Generalize methodology: URL → Subreddit → Domain → Source type',
    tags: ['reddit', 'geo', 'sources', 'offsite'],
    created_at: '2024-01-15',
    updated_at: '2024-03-10',
  },
  {
    id: 'dataforseo-historical',
    name: 'DataForSEO Historical Rankings',
    capability_id: 'seo-benchmark',
    status: 'validated',
    decision: 'industrialize',
    value: 5,
    maturity: 4,
    question:
      "Can we reconstruct historical SERP evolution for any keyword set using DataForSEO's historical index?",
    learnings: [
      {
        text: 'Historical data available up to 3 years back for most markets',
        type: 'finding',
      },
      {
        text: 'Pagination limits require batching queries efficiently',
        type: 'finding',
      },
      {
        text: 'Position tracking accurate within ±1 position vs. live data',
        type: 'finding',
      },
    ],
    inputs: ['Keyword list', 'Market (lang/geo)', 'Date range'],
    tool_ids: ['dataforseo', 'python', 'supabase'],
    clients: ['Decathlon', 'Leroy Merlin', 'Internal'],
    related_ids: ['competitor-gap', 'openseo-benchmark'],
    next_experiment:
      'Integrate as historical baseline into competitor benchmark pipeline',
    tags: ['dataforseo', 'rankings', 'benchmark', 'historical'],
    created_at: '2023-11-01',
    updated_at: '2024-02-28',
  },
  {
    id: 'ard-discovery',
    name: 'ARD / Knowledge Graph Discovery',
    capability_id: 'agentic',
    status: 'testing',
    decision: 'deepen',
    value: 4,
    maturity: 2,
    question:
      'Can we detect when AI agents discover a brand or service via structured data (ARD / Knowledge Graphs)?',
    learnings: [
      {
        text: 'Knowledge Graph entries correlate with increased LLM citation frequency',
        type: 'finding',
      },
      {
        text: 'ARD format is still inconsistently supported across LLM providers',
        type: 'warning',
      },
      {
        text: 'Schema.org coverage is a strong predictor of agentic discoverability',
        type: 'finding',
      },
    ],
    inputs: ['Brand entity list', 'LLM outputs', 'Schema.org audit'],
    tool_ids: ['openai', 'python', 'semactic'],
    clients: ['Internal R&D'],
    related_ids: ['mcp-agentic', 'llm-citation-freq'],
    next_experiment: 'Build MCP server for real-time agentic discovery monitoring',
    tags: ['ard', 'knowledge-graph', 'agentic', 'schema'],
    created_at: '2024-02-01',
    updated_at: '2024-04-05',
  },
  {
    id: 'openseo-benchmark',
    name: 'OpenSEO Benchmark Test',
    capability_id: 'seo-benchmark',
    status: 'failed',
    decision: 'replace',
    value: 2,
    maturity: 2,
    question:
      'Can OpenSEO replace SEOctopus for our competitive benchmark workflow?',
    learnings: [
      {
        text: 'Historical data limited to 6 months — insufficient for trend analysis',
        type: 'blocker',
      },
      {
        text: 'API rate limits too restrictive for batch competitor analysis',
        type: 'blocker',
      },
      {
        text: 'Data quality comparable to DataForSEO but with fewer features',
        type: 'finding',
      },
    ],
    inputs: ['Competitor keyword sets', 'API credentials'],
    tool_ids: ['python'],
    clients: ['Internal'],
    related_ids: ['dataforseo-historical'],
    tags: ['benchmark', 'api', 'competitor'],
    created_at: '2023-10-01',
    updated_at: '2023-12-15',
  },
  {
    id: 'robots-monitor',
    name: 'Robots.txt / Crawl Monitor',
    capability_id: 'technical-seo',
    status: 'production',
    decision: 'keep',
    value: 5,
    maturity: 5,
    question:
      'Can we automatically detect critical crawl configuration changes (robots.txt, sitemaps) before they cause indexation issues?',
    learnings: [
      {
        text: 'Caught 2 critical accidental disallow: / directives in production',
        type: 'finding',
      },
      {
        text: 'Sitemap diff detection identifies new/removed URL patterns within hours',
        type: 'finding',
      },
      {
        text: 'False positive rate <2% with URL normalization',
        type: 'finding',
      },
    ],
    inputs: ['Domain list', 'Previous robots.txt snapshot', 'Sitemap URLs'],
    tool_ids: ['python', 'supabase', 'screaming-frog'],
    clients: ['Decathlon', 'Leroy Merlin', 'Doctolib'],
    related_ids: [],
    tags: ['technical', 'crawl', 'monitoring', 'robots'],
    created_at: '2023-06-01',
    updated_at: '2024-03-20',
  },
  {
    id: 'geo-source-analysis',
    name: 'GEO Source Frequency Analysis',
    capability_id: 'geo-sources',
    status: 'validated',
    decision: 'deepen',
    value: 4,
    maturity: 3,
    question:
      'Which source types (Reddit, Wikipedia, publishers, brands) are most cited by LLMs, and how does this vary by query intent?',
    learnings: [
      {
        text: 'UGC (Reddit, forums) cited significantly more for opinion/advice queries',
        type: 'finding',
      },
      {
        text: 'Publisher authority domains dominate factual/YMYL queries',
        type: 'finding',
      },
      {
        text: "Brand own domains cited less than expected — UGC is dominant",
        type: 'finding',
      },
      {
        text: 'Source frequency varies significantly across LLM providers',
        type: 'warning',
      },
    ],
    inputs: ['Semactic GEO reports', 'Query set', 'LLM outputs'],
    tool_ids: ['semactic', 'python', 'openai'],
    clients: ['Decathlon', 'Leroy Merlin'],
    related_ids: ['reddit-source-impact', 'llm-citation-freq'],
    next_experiment: 'Build source taxonomy classifier to automate categorization',
    tags: ['geo', 'sources', 'llm', 'citation'],
    created_at: '2024-01-20',
    updated_at: '2024-04-01',
  },
  {
    id: 'llm-citation-freq',
    name: 'LLM Citation Frequency Tracking',
    capability_id: 'geo-sources',
    status: 'testing',
    decision: 'deepen',
    value: 4,
    maturity: 3,
    question:
      'Can we track how citation frequency for a specific domain/source evolves over time in LLM responses?',
    learnings: [
      {
        text: 'Citation frequency is a viable proxy for GEO visibility',
        type: 'finding',
      },
      {
        text: 'Frequency varies significantly by LLM temperature and prompt phrasing',
        type: 'warning',
      },
    ],
    inputs: ['Domain list', 'Query set', 'LLM API'],
    tool_ids: ['openai', 'python', 'supabase'],
    clients: ['Internal R&D'],
    related_ids: ['geo-source-analysis', 'reddit-source-impact', 'ard-discovery'],
    next_experiment: 'Automate citation tracking at scale across 100+ domains',
    tags: ['llm', 'citation', 'geo', 'tracking'],
    created_at: '2024-02-15',
    updated_at: '2024-04-10',
  },
  {
    id: 'competitor-gap',
    name: 'Competitor Keyword Gap Analysis',
    capability_id: 'keyword-intel',
    status: 'production',
    decision: 'keep',
    value: 5,
    maturity: 5,
    question:
      "How do we systematically identify keyword opportunities where competitors rank but we don't?",
    learnings: [
      {
        text: 'Clustering by intent first dramatically improves gap quality',
        type: 'finding',
      },
      {
        text: "DataForSEO 'top pages' + keyword data gives best coverage",
        type: 'finding',
      },
    ],
    inputs: ['Competitor domains', 'Client domain', 'Target market'],
    tool_ids: ['dataforseo', 'python', 'seoctopus'],
    clients: ['Decathlon', 'Leroy Merlin', 'Doctolib', 'Cdiscount'],
    related_ids: ['dataforseo-historical', 'content-gap-scoring'],
    tags: ['keywords', 'competitor', 'gap', 'benchmark'],
    created_at: '2023-05-01',
    updated_at: '2024-01-15',
  },
  {
    id: 'semantic-clustering',
    name: 'Semantic Keyword Clustering v2',
    capability_id: 'keyword-intel',
    status: 'validated',
    decision: 'industrialize',
    value: 5,
    maturity: 4,
    question:
      'Can we replace rule-based keyword clustering with embedding-based clustering to better capture semantic relationships?',
    learnings: [
      {
        text: 'Embedding-based clustering 3× more coherent than n-gram approach in user testing',
        type: 'finding',
      },
      {
        text: 'Optimal cluster count varies by category — auto-detection needed',
        type: 'finding',
      },
      {
        text: 'Processing cost manageable at <$0.01 per 1,000 keywords',
        type: 'finding',
      },
    ],
    inputs: ['Keyword list + search volumes', 'Embedding model'],
    tool_ids: ['openai', 'python', 'dataforseo'],
    clients: ['Decathlon', 'Leroy Merlin'],
    related_ids: ['competitor-gap', 'content-gap-scoring'],
    next_experiment: 'Cluster at scale with DuckDB + parquet for 10M+ keywords',
    tags: ['keywords', 'clustering', 'embedding', 'nlp'],
    created_at: '2024-01-01',
    updated_at: '2024-03-25',
  },
  {
    id: 'youtube-source',
    name: 'YouTube Source Impact',
    capability_id: 'offsite-geo',
    status: 'idea',
    decision: null,
    value: 3,
    maturity: 1,
    question:
      'Does YouTube video content (transcripts, descriptions) influence LLM citation of that channel or topic?',
    learnings: [],
    inputs: ['YouTube channel list', 'Video transcripts', 'LLM outputs'],
    tool_ids: ['python', 'openai'],
    clients: [],
    related_ids: ['reddit-source-impact', 'geo-source-analysis'],
    tags: ['youtube', 'video', 'geo', 'sources'],
    created_at: '2024-04-01',
    updated_at: '2024-04-01',
  },
  {
    id: 'mcp-agentic',
    name: 'MCP Agentic Discovery Test',
    capability_id: 'agentic',
    status: 'testing',
    decision: 'deepen',
    value: 4,
    maturity: 2,
    question:
      'Can exposing services via MCP improve their discovery and usage by AI agents?',
    learnings: [
      {
        text: 'MCP adoption accelerating — Claude.ai, Cursor, Windsurf all support it',
        type: 'finding',
      },
      {
        text: 'Well-documented MCP tools get called significantly more than undocumented ones',
        type: 'finding',
      },
    ],
    inputs: ['Service list', 'API documentation', 'Agent test prompts'],
    tool_ids: ['python', 'openai'],
    clients: ['Internal R&D'],
    related_ids: ['ard-discovery'],
    next_experiment: 'Build MCP server exposing key SEO/GEO data endpoints',
    tags: ['mcp', 'agentic', 'api', 'discovery'],
    created_at: '2024-03-01',
    updated_at: '2024-04-12',
  },
  {
    id: 'content-gap-scoring',
    name: 'Content Gap Opportunity Scoring',
    capability_id: 'content-intel',
    status: 'validated',
    decision: 'deepen',
    value: 4,
    maturity: 3,
    question:
      'How do we score content gap opportunities by combining search volume, competition, and intent alignment?',
    learnings: [
      {
        text: 'volume × (1/competition) × intent_score outperforms pure volume ranking',
        type: 'finding',
      },
      {
        text: 'LLM-based intent classification is more accurate than rule-based for long-tail',
        type: 'finding',
      },
    ],
    inputs: ['Keyword gaps', 'Competition data', 'Intent labels'],
    tool_ids: ['dataforseo', 'openai', 'python'],
    clients: ['Decathlon', 'Cdiscount'],
    related_ids: ['competitor-gap', 'semantic-clustering'],
    next_experiment: 'Add GEO opportunity scoring layer (LLM citation potential)',
    tags: ['content', 'gap', 'scoring', 'opportunity'],
    created_at: '2024-02-01',
    updated_at: '2024-04-08',
  },
]

export const relations: Relation[] = [
  {
    id: 'r1',
    source_id: 'dataforseo',
    source_type: 'tool',
    target_id: 'dataforseo-historical',
    target_type: 'experiment',
    relation_type: 'feeds',
  },
  {
    id: 'r2',
    source_id: 'dataforseo',
    source_type: 'tool',
    target_id: 'competitor-gap',
    target_type: 'experiment',
    relation_type: 'feeds',
  },
  {
    id: 'r3',
    source_id: 'dataforseo',
    source_type: 'tool',
    target_id: 'semantic-clustering',
    target_type: 'experiment',
    relation_type: 'feeds',
  },
  {
    id: 'r4',
    source_id: 'dataforseo-historical',
    source_type: 'experiment',
    target_id: 'competitor-gap',
    target_type: 'experiment',
    relation_type: 'enables',
  },
  {
    id: 'r5',
    source_id: 'semactic',
    source_type: 'tool',
    target_id: 'reddit-source-impact',
    target_type: 'experiment',
    relation_type: 'feeds',
  },
  {
    id: 'r6',
    source_id: 'semactic',
    source_type: 'tool',
    target_id: 'geo-source-analysis',
    target_type: 'experiment',
    relation_type: 'feeds',
  },
  {
    id: 'r7',
    source_id: 'reddit-source-impact',
    source_type: 'experiment',
    target_id: 'geo-source-analysis',
    target_type: 'experiment',
    relation_type: 'validates',
  },
  {
    id: 'r8',
    source_id: 'reddit-source-impact',
    source_type: 'experiment',
    target_id: 'youtube-source',
    target_type: 'experiment',
    relation_type: 'extends',
  },
  {
    id: 'r9',
    source_id: 'ard-discovery',
    source_type: 'experiment',
    target_id: 'mcp-agentic',
    target_type: 'experiment',
    relation_type: 'related_to',
  },
  {
    id: 'r10',
    source_id: 'competitor-gap',
    source_type: 'experiment',
    target_id: 'content-gap-scoring',
    target_type: 'experiment',
    relation_type: 'enables',
  },
  {
    id: 'r11',
    source_id: 'semantic-clustering',
    source_type: 'experiment',
    target_id: 'content-gap-scoring',
    target_type: 'experiment',
    relation_type: 'enables',
  },
  {
    id: 'r12',
    source_id: 'llm-citation-freq',
    source_type: 'experiment',
    target_id: 'geo-source-analysis',
    target_type: 'experiment',
    relation_type: 'extends',
  },
  {
    id: 'r13',
    source_id: 'openseo-benchmark',
    source_type: 'experiment',
    target_id: 'dataforseo-historical',
    target_type: 'experiment',
    relation_type: 'replaced_by',
  },
]
